/**
 * Compact model catalog for the mobile Marketplace — snapshot of the
 * OpenRouter catalog with a short specialty per model (mirrors web /models).
 */
export interface CatalogModel {
  id: string;
  name: string;
  provider: string;
  spec: string;
  inM: number;
  outM: number;
  ctx: number;
}

export const MODEL_SPECS = [
  "All",
  "Reasoning",
  "Coding",
  "Vision",
  "Video understanding",
  "Image generation",
  "Audio & speech",
  "Free & fast",
] as const;

export const MODEL_CATALOG: CatalogModel[] = [
  {
    id: "inclusionai/ling-3.0-tiny:free",
    name: "inclusionAI: Ling 3.0 Tiny (free)",
    provider: "Inclusionai",
    spec: "Agents & tools",
    inM: 0.0,
    outM: 0.0,
    ctx: 262144,
  },
  {
    id: "meta/muse-spark-1.2",
    name: "Meta: Muse Spark 1.2",
    provider: "Meta",
    spec: "Video understanding",
    inM: 1.25,
    outM: 4.25,
    ctx: 1048576,
  },
  {
    id: "qwen/qwen3.8-max",
    name: "Qwen: Qwen3.8 Max",
    provider: "Qwen",
    spec: "Video understanding",
    inM: 2.0,
    outM: 6.0,
    ctx: 1000000,
  },
  {
    id: "~deepseek/deepseek-v4-flash-latest",
    name: "DeepSeek V4 Flash Latest",
    provider: "~Deepseek",
    spec: "General chat",
    inM: 0.08,
    outM: 0.252,
    ctx: 1048576,
  },
  {
    id: "deepseek/deepseek-v4-flash-0731",
    name: "DeepSeek: DeepSeek V4 Flash 0731",
    provider: "Deepseek",
    spec: "Reasoning",
    inM: 0.08,
    outM: 0.18,
    ctx: 1048576,
  },
  {
    id: "thinkingmachines/inkling-small",
    name: "Thinking Machines: Inkling Small",
    provider: "Thinkingmachines",
    spec: "Audio & speech",
    inM: 0.45,
    outM: 1.2,
    ctx: 524288,
  },
  {
    id: "qwen/qwen3.7-flash",
    name: "Qwen: Qwen3.7 Flash",
    provider: "Qwen",
    spec: "Video understanding",
    inM: 0.03,
    outM: 0.13,
    ctx: 1000000,
  },
  {
    id: "anthropic/claude-opus-5-fast",
    name: "Claude Opus 5 (Fast)",
    provider: "Anthropic",
    spec: "Vision",
    inM: 10.0,
    outM: 50.0,
    ctx: 1000000,
  },
  {
    id: "anthropic/claude-opus-5",
    name: "Claude Opus 5",
    provider: "Anthropic",
    spec: "Reasoning",
    inM: 5.0,
    outM: 25.0,
    ctx: 1000000,
  },
  {
    id: "anthropic/claude-opus-5:batch",
    name: "Claude Opus 5 (batch)",
    provider: "Anthropic",
    spec: "Reasoning",
    inM: 2.5,
    outM: 12.5,
    ctx: 1000000,
  },
  {
    id: "inclusionai/ling-3.0-flash",
    name: "Ling-3.0-flash",
    provider: "Inclusionai",
    spec: "Agents & tools",
    inM: 0.021,
    outM: 0.063,
    ctx: 262144,
  },
  {
    id: "poolside/laguna-s-2.1",
    name: "Poolside: Laguna S 2.1",
    provider: "Poolside",
    spec: "Coding",
    inM: 0.09,
    outM: 0.18,
    ctx: 1048576,
  },
  {
    id: "poolside/laguna-s-2.1:free",
    name: "Poolside: Laguna S 2.1 (free)",
    provider: "Poolside",
    spec: "Coding",
    inM: 0.0,
    outM: 0.0,
    ctx: 262144,
  },
  {
    id: "google/gemini-3.6-flash",
    name: "Google: Gemini 3.6 Flash",
    provider: "Google",
    spec: "Video understanding",
    inM: 1.5,
    outM: 7.5,
    ctx: 1048576,
  },
  {
    id: "google/gemini-3.6-flash:batch",
    name: "Google: Gemini 3.6 Flash (batch)",
    provider: "Google",
    spec: "Video understanding",
    inM: 0.75,
    outM: 3.75,
    ctx: 1048576,
  },
  {
    id: "google/gemini-3.5-flash-lite",
    name: "Google: Gemini 3.5 Flash Lite",
    provider: "Google",
    spec: "Video understanding",
    inM: 0.3,
    outM: 2.5,
    ctx: 1048576,
  },
  {
    id: "google/gemini-3.5-flash-lite:batch",
    name: "Google: Gemini 3.5 Flash Lite (batch)",
    provider: "Google",
    spec: "Video understanding",
    inM: 0.15,
    outM: 1.25,
    ctx: 1048576,
  },
  {
    id: "meituan/longcat-2.0",
    name: "Meituan: LongCat 2.0",
    provider: "Meituan",
    spec: "Coding",
    inM: 0.3,
    outM: 1.2,
    ctx: 1048756,
  },
  {
    id: "thinkingmachines/inkling",
    name: "Thinking Machines: Inkling",
    provider: "Thinkingmachines",
    spec: "Audio & speech",
    inM: 0.95,
    outM: 4.05,
    ctx: 1048576,
  },
  {
    id: "thinkingmachines/inkling:batch",
    name: "Thinking Machines: Inkling (batch)",
    provider: "Thinkingmachines",
    spec: "Audio & speech",
    inM: 0.5,
    outM: 2.025,
    ctx: 524288,
  },
  {
    id: "openrouter/auto-beta",
    name: "Auto Router (Beta)",
    provider: "Openrouter",
    spec: "Image generation",
    inM: -1000000.0,
    outM: -1000000.0,
    ctx: 2000000,
  },
  {
    id: "moonshotai/kimi-k3",
    name: "MoonshotAI: Kimi K3",
    provider: "Moonshotai",
    spec: "Reasoning",
    inM: 3.0,
    outM: 15.0,
    ctx: 1048576,
  },
  {
    id: "meta/muse-spark-1.1",
    name: "Meta: Muse Spark 1.1",
    provider: "Meta",
    spec: "Video understanding",
    inM: 1.25,
    outM: 4.25,
    ctx: 1048576,
  },
  {
    id: "kwaipilot/kat-coder-air-v2.5",
    name: "Kwaipilot: KAT-Coder-Air V2.5",
    provider: "Kwaipilot",
    spec: "Coding",
    inM: 0.15,
    outM: 0.6,
    ctx: 256000,
  },
  {
    id: "kwaipilot/kat-coder-pro-v2.5",
    name: "Kwaipilot: KAT-Coder-Pro V2.5",
    provider: "Kwaipilot",
    spec: "Coding",
    inM: 0.74,
    outM: 2.96,
    ctx: 256000,
  },
  {
    id: "openai/gpt-5.6-luna-pro",
    name: "OpenAI: GPT-5.6 Luna Pro",
    provider: "Openai",
    spec: "Reasoning",
    inM: 0.1,
    outM: 0.6,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-luna-pro:batch",
    name: "OpenAI: GPT-5.6 Luna Pro (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 0.1,
    outM: 0.6,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-luna",
    name: "OpenAI: GPT-5.6 Luna",
    provider: "Openai",
    spec: "Reasoning",
    inM: 0.1,
    outM: 0.6,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-luna:batch",
    name: "OpenAI: GPT-5.6 Luna (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 0.1,
    outM: 0.6,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-terra-pro",
    name: "OpenAI: GPT-5.6 Terra Pro",
    provider: "Openai",
    spec: "Reasoning",
    inM: 1.0,
    outM: 6.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-terra-pro:batch",
    name: "OpenAI: GPT-5.6 Terra Pro (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 1.0,
    outM: 6.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-terra",
    name: "OpenAI: GPT-5.6 Terra",
    provider: "Openai",
    spec: "Reasoning",
    inM: 1.0,
    outM: 6.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-terra:batch",
    name: "OpenAI: GPT-5.6 Terra (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 1.0,
    outM: 6.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-sol-pro",
    name: "OpenAI: GPT-5.6 Sol Pro",
    provider: "Openai",
    spec: "Reasoning",
    inM: 5.0,
    outM: 30.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-sol-pro:batch",
    name: "OpenAI: GPT-5.6 Sol Pro (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 2.5,
    outM: 15.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-sol",
    name: "OpenAI: GPT-5.6 Sol",
    provider: "Openai",
    spec: "Reasoning",
    inM: 5.0,
    outM: 30.0,
    ctx: 1050000,
  },
  {
    id: "openai/gpt-5.6-sol:batch",
    name: "OpenAI: GPT-5.6 Sol (batch)",
    provider: "Openai",
    spec: "Reasoning",
    inM: 2.5,
    outM: 15.0,
    ctx: 1050000,
  },
  {
    id: "x-ai/grok-4.5",
    name: "SpaceXAI: Grok 4.5",
    provider: "X Ai",
    spec: "Coding",
    inM: 2.0,
    outM: 6.0,
    ctx: 500000,
  },
  {
    id: "~x-ai/grok-latest",
    name: "xAI: Grok Latest",
    provider: "~X Ai",
    spec: "Vision",
    inM: 2.0,
    outM: 6.0,
    ctx: 500000,
  },
  {
    id: "aion-labs/aion-3.0-mini",
    name: "AionLabs: Aion-3.0-Mini",
    provider: "Aion Labs",
    spec: "General chat",
    inM: 0.7,
    outM: 1.4,
    ctx: 131072,
  },
  {
    id: "aion-labs/aion-3.0",
    name: "AionLabs: Aion-3.0",
    provider: "Aion Labs",
    spec: "General chat",
    inM: 3.0,
    outM: 6.0,
    ctx: 131072,
  },
  {
    id: "tencent/hy3",
    name: "Tencent: Hy3",
    provider: "Tencent",
    spec: "Reasoning",
    inM: 0.132,
    outM: 0.528,
    ctx: 262144,
  },
  {
    id: "poolside/laguna-xs-2.1",
    name: "Poolside: Laguna XS 2.1",
    provider: "Poolside",
    spec: "Coding",
    inM: 0.06,
    outM: 0.12,
    ctx: 262144,
  },
  {
    id: "poolside/laguna-xs-2.1:free",
    name: "Poolside: Laguna XS 2.1 (free)",
    provider: "Poolside",
    spec: "Coding",
    inM: 0.0,
    outM: 0.0,
    ctx: 262144,
  },
  {
    id: "anthropic/claude-sonnet-5",
    name: "Anthropic: Claude Sonnet 5",
    provider: "Anthropic",
    spec: "Reasoning",
    inM: 2.0,
    outM: 10.0,
    ctx: 1000000,
  },
  {
    id: "anthropic/claude-sonnet-5:batch",
    name: "Anthropic: Claude Sonnet 5 (batch)",
    provider: "Anthropic",
    spec: "Reasoning",
    inM: 1.0,
    outM: 5.0,
    ctx: 1000000,
  },
  {
    id: "google/gemini-3.1-flash-lite-image",
    name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
    provider: "Google",
    spec: "Image generation",
    inM: 0.25,
    outM: 1.5,
    ctx: 65536,
  },
  {
    id: "nex-agi/nex-n2-mini",
    name: "Nex AGI: Nex-N2-Mini",
    provider: "Nex Agi",
    spec: "Coding",
    inM: 0.025,
    outM: 0.1,
    ctx: 262144,
  },
];
